Train:
  exp_name:
  num_steps: 50000
  infer: False
  infer_state: False
  debug_model: False


Frontend:
  fe_type: Point2Skeleton
  fe_skelpoint_num: 100
  fe_particles_num: 1000
  fe_load_skelnet_path: ../weights/weights-skelpoint.pth
  fe_load_gae_path: ../weights/weights-gae.pth
  fe_save_result_path: ../results/



Algo:
  name: SoftGPT

  mode: Particle  # Env mode, Particle or Image or Graph
  homo_graph: False  # use homogenous graph or heterogeneous graph
  static_graph: False  # use static graph or dynamic graph

  use_imitation: True  # use imitation dataset or not
  use_lagrange: True  # use lagrange imitation or not

  use_softgpt_think: True
  think_horizon: 16
  think_discount: 0.2

  softgpt_update_flag: False
  softgpt_update_interval: 250
  softgpt_update_lr: 0.0003

  rew_update_flag: False
  rew_update_interval: 250
  rew_update_lr: 0.0003

  lr: 0.1
  softness: 666.
  optim: Adam  # Adam, Momentum

  ckpt_path:


